# Generated by Django 4.1.2 on 2022-11-08 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordForgottenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_end', models.DateTimeField(verbose_name='validity')),
                ('link', models.CharField(max_length=300, verbose_name='link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
