# Generated by Django 4.1.2 on 2022-12-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_alter_comment_likes_alter_tag_name'),
        ('users', '0004_passwordforgottenrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(to='travels.tag', verbose_name='Preferred tags'),
        ),
    ]
