# Generated by Django 4.1.2 on 2022-10-27 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='shares',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='travels.post', verbose_name='Shared post'),
        ),
    ]
