# Generated by Django 4.1.2 on 2022-10-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_alter_post_likes_alter_post_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.post', verbose_name='Shared post'),
        ),
    ]
