# Generated by Django 4.1.2 on 2022-12-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_location_tag_post_location_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='travels.tag', verbose_name='Tags'),
        ),
    ]
