# Generated by Django 4.1.2 on 2022-12-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_alter_comment_likes_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Text content'),
        ),
    ]
