# Generated by Django 4.1.2 on 2022-12-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='post/images', verbose_name='image'),
        ),
    ]
